name: .NET Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create version
      id: version
      run: echo "::set-output name=version::${${{ steps.tag_version.outputs.new_tag }}:1}"
    - name: Pack
      run: dotnet pack --configuration Release --no-build /p:Version=${{ steps.version.outputs.version }}
    - name: Push package to NuGet.org
      run: dotnet nuget push -k ${{ secrets.NUGET_ORG_API_KEY }} -s https://api.nuget.org/v3/index.json
      shell: bash
    - name: Push package to GitHub.com
      run: dotnet nuget push -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/mikaeldui/index.json
      shell: bash
      
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.nupkg"
        token: ${{ github.token }}
        name: ${{ inputs.version }}
        tag: ${{ steps.tag_version.outputs.new_tag }}
        body: |
          You can install [this specific version from NuGet.org](https://www.nuget.org/packages/MikaelDui.ChampionMasteryGg.Client/${{ steps.version.outputs.version }}) using either of these commands:
          Using **Package Manager Console**:
              PM> Install-Package MikaelDui.ChampionMasteryGg.Client --Version ${{ inputs.version }}
          Using the **.NET CLI**:
              dotnet add package MikaelDui.ChampionMasteryGg.Client --version ${{ inputs.version }}
          But it's preferable to use **floating versions**.
            ${{ steps.tag_version.outputs.changelog }}
