name: .NET Build & Test

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: '*'
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Create tag dry run
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
        
    - name: Create version
      id: version
      run: |
        version=$(echo ${{steps.tag_version.outputs.new_tag}} | cut -c2-)
        echo "::set-output name=version::$version"
        
    - name: SemVer suffix
      id: semver
      uses: mikaeldui/actions/nupkg/semver-suffix@main
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=${{ steps.version.outputs.version }}${{ steps.semver.outputs.suffix }}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      # Pack & Publish
      
    - name: 'Pack & Publish Artifact'
      uses: mikaeldui/actions/nupkg/dotnet/pack-and-publish-artifact@main
      with:
        version: ${{ steps.version.outputs.version }}${{ steps.semver.outputs.suffix }}
        project_directory: ./
        relative_package_path: src/ChampionMasteryGg.Client.MultiTarget/bin/Release/*.nupkg
        
